openapi: 3.1.0
info:
  title: SCIM Device Schema
  version: 1.0.0

components:
  schemas:
    Group:
      type: object
      description: Group entries for Devices
      properties:
        value:
          type: string
          description: the unique identifier of a group,
                       typically a UUID.
          readOnly: false
          writeOnly: false
        display:
          type: string
          description: a display string for the group.
          readOnly: false
          writeOnly: false
        $ref:
          type: string
          format: uri
          description: reference to the group object

    Device:
      description: Device account
      type: object
      properties:
        displayName:
          type: string
          description: "Human readable name of the device, suitable
                        for displaying to end-users. For example,
                       'BLE Heart Monitor' etc."
          readOnly: false
          writeOnly: false
        active:
          type: boolean
          description: A mutable boolean value indicating the device
                       administrative status. If set TRUE, the
                       commands (such as connect, disconnect,
                       subscribe) that control app sends to the
                       controller for the devices will be processeed
                       by the controller.  If set FALSE, any command
                       comming from the control app for the device
                       will be rejected by the controller.
          readOnly: false
          writeOnly: false
        mudUrl:
          type: string
          format: uri
          description: A URL to MUD file of the device (RFC 8520). It
                       is added for future use. Current usage is not 
                       defined yet.
          readOnly: false
          writeOnly: false
        groups:
          type: array
          description: list of groups device belongs to
          items:
            $ref: '#/components/schemas/Group'

      required:
        - active
      additionalProperties: false
      allOf:
        - $ref: '#/components/schemas/CommonAttributes'
    CommonAttributes:
      type: object
      properties:
        schemas:
          type: array
          items:
            type: string
            enum:
              - urn:ietf:params:scim:schemas:core:2.0:Device
          description: The list of schemas that define the resource.
        id:
          type: string
          format: uri
          description: The unique identifier for a resource.
          readOnly: true
          writeOnly: false
        externalId:
          type: string
          description: An identifier for the resource that is defined
                       by the provisioning client.
          readOnly: false
          writeOnly: false
        meta:
          type: object
          readOnly: true
          properties:
            resourceType:
              type: string
              description: The name of the resource type of the 
                           resource.
              readOnly: true
              writeOnly: false
            location:
              type: string
              format: uri
              description: The URI of the resource being returned.
              readOnly: true
              writeOnly: false
            created:
              type: string
              format: date-time
              description: The date and time the resource was added
                           to the service provider.
              readOnly: true
              writeOnly: false
            lastModified:
              type: string
              format: date-time
              description: The most recent date and time that the 
                           details of this resource were updated at
                           the service provider.
              readOnly: true
              writeOnly: false
            version:
              type: string
              description: The version of the resource. 
              readOnly: true
              writeOnly: false
          additionalProperties: false
