openapi: 3.1.0
info:
  title: SCIM Fido Device Onboarding Extension Schema
  version: 1.0.0

components:
  schemas:
    FDODevice:
      type: object
      description: FIDO Device Onboarding Extension
      properties:
        schemas:
          type: array
          items:
            type: string
            enum:
              - urn:ietf:params:scim:schemas:extension:fido-device-onboard:2.0:Devices
        urn:ietf:params:scim:schemas:extension:fido-device-onboard:2.0:Devices:
          $ref: '#/components/schemas/FDODeviceExtension'
          required: true
    FDODeviceExtension:
      type: object
      properties:
        fdoVoucher:
          type: string
          description: A FIDO Device Onboard (FDO) Voucher
          nullable: false
          readOnly: false
          writeOnly: false
      required:
        - fdoVoucher
      description: Device Extension for a FIDO Device Onboard (FDO)
