openapi: 3.1.0
info:
  title: SCIM Bluetooth Extension Schema
  version: 1.0.0

components:
  schemas:
    BleDevice:
      type: object
      description: BLE Device schema.
      properties:
        schemas:
          type: array
          items:
            type: string
            enum:
              - urn:ietf:params:scim:schemas:extension:ble:2.0:Device
        urn:ietf:params:scim:schemas:extension:ble:2.0:Device:
          $ref: '#/components/schemas/BleDeviceExtension'
          required: true
    BleDeviceExtension:
      type: object
      properties:
        versionSupport:
          type: array
          items:
            type: string
          description: Provides a list of all the BLE versions 
                       supported by the device. For example, 
                       [4.1, 4.2, 5.0, 5.1, 5.2, 5.3].
          nullable: false
          readOnly: false
          writeOnly: false

        deviceMacAddress:
          type: string
          description: It is the public MAC address assigned by the 
                       manufacturer. It is unique 48 bit value. The
                       regex pattern is 
                       ^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}.
          nullable: false
          readOnly: false
          writeOnly: false

        isRandom:
          type: boolean
          description: AddressType flag is taken from the BLE core 
                       specifications 5.3. If FALSE, the device is 
                       using public MAC address. If TRUE, device is 
                       using a random address.
          nullable: false
          readOnly: false
          writeOnly: false
        
        separateBroadcastAddress:
          type: string
          description: "When present, this address is used for 
                        broadcasts/advertisements.  This value MUST NOT
                        be set when an IRK is provided.  Its form is 
                        the same as deviceMa`cAddress."
          nullable: false
          readOnly: false
          writeOnly: false

        irk:
          type: string
          description: Identity resolving key, which is unique for 
                       every device. It is used to resolve random 
                       address.
          nullable: true
          readOnly: false
          writeOnly: true
        mobility:
          type: boolean
          description: If set to True, the BLE device will 
                       automatically connect to the closest AP. For 
                       example, BLE device is connected with AP-1 and 
                       moves out of range but comes in range of AP-2, 
                       it will be disconnected with AP-1 and connects 
                       with AP-2.
          nullable: false
          readOnly: false
          writeOnly: false
        pairingMethods:
          type: array
          items:
            type: string
          description: List of pairing methods associated with the 
                       ble device, stored as schema URI.
          nullable: true
          readOnly: false
          writeOnly: false
        urn:ietf:params:scim:schemas:extension:pairingNull:2.0:Device:
          $ref: '#/components/schemas/NullPairing'
          required: false
        urn:ietf:params:scim:schemas:extension:pairingJustWorks:2.0:Device:
          $ref: '#/components/schemas/PairingJustWorks'
          required: false
        urn:ietf:params:scim:schemas:extension:pairingPassKey:2.0:Device:
          $ref: '#/components/schemas/PairingPassKey'
          required: false
        urn:ietf:params:scim:schemas:extension:pairingOOB:2.0:Device:
          $ref: '#/components/schemas/PairingOOB'
          required: false
      required:
        - versionSupport
        - deviceMacAddress
        - AddressType
        - pairingMethods
      additionalProperties: false

    NullPairing:
      type: object

    PairingJustWorks:
      type: object
      description: Just works pairing method for ble
      properties:
        key:
          type: integer
          description: Just works does not have any key value. For 
                       completeness, it is added with a key value
                       'null'.
          nullable: false
          readOnly: false
          writeOnly: false
      required:
        - key

    PairingPassKey:
      type: object
      description: Pass key pairing method for ble
      properties:
        key:
          type: integer
          description: A six digit passkey for ble device.
                       The pattern of key is ^[0-9]{6}$.
          nullable: false
          readOnly: false
          writeOnly: true
      required:
        - key

    PairingOOB:
      type: object
      description: Out-of-band pairing method for BLE
      properties:
        key:
          type: string
          description: The OOB key value for ble device.
          nullable: false
          readOnly: false
          writeOnly: false
        randomNumber:
          type: integer
          description: Nonce added to the key
          nullable: false
          readOnly: false
          writeOnly: true
        confirmationNumber:
          type: integer
          description: Some solutions require a confirmation number 
                       in the RESTful message exchange.
          nullable: true
          readOnly: false
          writeOnly: true
      required:
        - key
        - randomNumber
