openapi: 3.1.0
info:
  title: SCIM Endpoint extension schema
  version: 1.0.0


components:
  schemas:
    EndpointAppsExt:
      type: object
      properties:
        applications:
          $ref: '#/components/schemas/applications'
        
        deviceControlEnterpriseEndpoint:
          type: string
          format: url
          description: The URL of the enterprise endpoint which device
                       control apps use to reach enterprise network 
                       gateway.
          readOnly: true
          writeOnly: false
        
        telemetryEnterpriseEndpoint:
          type: string
          format: url
          description: The URL of the enterprise endpoint which 
                       telemetry apps use to reach enterprise network 
                       gateway.
          readOnly: true
          writeOnly: false

      required:
        - applications
        - deviceControlEnterpriseEndpoint
        
    applications:
      type: array
      items:
        value:
          type: string
          description: The identifier of the endpointApp.
          readOnly: false
          writeOnly: false
        ref:
          type: string
          format: uri
          description: The URI of the corresponding 'EndpointApp' 
                      resource which will control or obtain data from 
                      the device.
          readOnly: true
          writeOnly: false
      required:
        - value
        - ref

   
